behaviors:
  connect_4_ai:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 1280
      learning_rate: 0.0005
      beta: 0.01
      epsilon: 0.15
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 4
      memory:
        memory_size: 64
        sequence_length: 42
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 10
    threaded: false
    max_steps: 100000000
    time_horizon: 42
    summary_freq: 10000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 10000
      swap_steps: 10000
      team_change: 50000