behaviors:
  connect_4_ai:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 640
      learning_rate: 0.0004
      beta: 0.002
      epsilon: 0.15
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: constant
      beta_schedule: constant
      epsilon_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 4
      memory:
        memory_size: 64
        sequence_length: 42
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    threaded: false
    max_steps: 100000000
    time_horizon: 42
    summary_freq: 10000